version: '3.9'
services:
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  web:
    build: .
    command: /bin/bash
    volumes:
      - ./app:/app
    environment:
      - BUNDLE_APP_CONFIG
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    depends_on:
      - db
volumes:
  data: