databases:
  - name: 20230316_kashika
    databaseName: 20230316_kashika
    user: 20230316_kashika

services:
  - type: web
    name: 20230316_kashika
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: 20230316_kashika
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false